# Generated by Django 5.2.4 on 2025-07-13 18:44

import django.db.models.deletion
import eleccpresidenciales.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, validators=[eleccpresidenciales.validators.valida_sigla])),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[eleccpresidenciales.validators.valida_texto_sin_numero])),
                ('apellido', models.CharField(max_length=100, validators=[eleccpresidenciales.validators.valida_texto_sin_numero])),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, max_length=8, null=True, validators=[eleccpresidenciales.validators.valida_numeros])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente')], max_length=150)),
                ('habilitado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.eleccion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.partido')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.votante')),
            ],
        ),
        migrations.CreateModel(
            name='VotanteEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.eleccion')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.votante')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.candidato')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.eleccion')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccpresidenciales.votante')),
            ],
        ),
    ]
